// Ported verbatim from D:/py_yaddessa/temp_works/src/lib/chem-lab-data.ts (itself
// GENERATED by that project's scripts/extract_chem_lab_data.py) — see
// prisma/real-data-seed.ts's own header for the full provenance chain.
//
// Source: real_data/Laboratory list for chem.docx, the Chemical Engineering
// department's own equipment register. Names, descriptions, experiment lists,
// conditions and photographs are theirs; nothing here is invented. The only change
// from the upstream file is `images`: bare filenames instead of `/images/equipment/…`
// web paths, resolved against prisma/seed-assets/equipment/ at seed time (see that
// directory's own README note) rather than served as static Next.js public assets.

export interface ChemEquipmentRecord {
  labCategory: string;
  name: string;
  description: string;
  experiments: string;
  status: string;
  images: string[];
}

export const CHEM_EQUIPMENT_RECORDS: ChemEquipmentRecord[] = [
  {
    labCategory: "Mechanical Unit Operation",
    name: "CEL-MKII Fixed and Fluidized Bed Apparatus",
    description:
      "The apparatus comprises three clear acrylic columns mounted above a molded ABS base. The base contains a water reservoir with a variable speed submersible pump that pumps water through an electronic flow meter into the base of the left-hand column. This column features an overflow pipe that returns the water back into the sump.",
    experiments:
      "Determining the voidage of granular material, Flow through fixed and fluidized beds using water and air as the fluidizing medium, the pressure drop (head loss) across the beds with different particle sizes, Verification of Carman-Kozeny's equation, compare the predicted onset of fluidization with the measured pressure drop, compare the onset of fluidization between two particle sizes, to observe the onset of fluidization and differentiate between the characteristics of a fixed bed and a fluidized bed for different particle sizes, investigate the difference between different sized granular material on fluidization characteristics, using air as the fluidizing medium, demonstration of liquefaction and liquefied soil phenomena (e.g. quicksand), to investigate the characteristics associated with water flowing vertically upwards through beds of different granular material",
    status: "Functional",
    images: ["cel-mkii-fixed-and-fluidized-bed-apparatus-1.jpg"],
  },
  {
    labCategory: "Mechanical Unit Operation",
    name: "CEK MKII - Fluid Mixing Apparatus",
    description:
      "The apparatus comprises a clear acrylic mixing vessel mounted on a stainless steel base. Above this is mounted a variable-speed electronic mixer with electronic torque measurement incorporated.",
    experiments:
      "Observe the various flow patterns that can be achieved by the use of different impellers with and without the use of baffles, show how the power consumed by a mixer varies with speed, type of impeller, and with the inclusion of baffles, Study torque/power/speed characteristics of different impellors, observe how different types of impeller turning at different speeds influence the rate of dispersion of solids throughout the liquid, observe the effectiveness of different impeller configurations running at different speeds, with and without baffles, on the mixing of immiscible liquids, study the effectiveness of different impeller configurations running at different speeds, with and without baffles, on the rate of mixing an electrolyte in water, investigation of how mixing time affects the quality of mixing, investigate the effect of flat blade paddles, propellers and agitators on mixing, predict the power absorbed by a large mixer using the Fluid Mixing Apparatus provided as a model and to draw a characteristic mixing curve, observe the effect of temperature on the viscosity of fluids and the corresponding changes in stirring characteristics",
    status: "Functional",
    images: ["cek-mkii-fluid-mixing-apparatus-1.jpg"],
  },
  {
    labCategory: "Mechanical Unit Operation",
    name: "Jaw Crusher",
    description:
      "It has two Jaws, between which material is being crushed. Feed enters from a funnel shaped casing, open at the top, is pivoted at the top of the machine. One jaw is stationary and the other is moving. This moving Jaw gets motion by eccentric shaft. Solids caught in the V shaped space between two Jaws and broken and re-broken till they passed out from the bottom. Due to the main motion at the bottom of V-shaped there is very little tendency for a crusher of this kind to chock. The main force for the crushing is compression.",
    experiments: "To determine reduction ratio and constant values for Rittinger's law, Kick's law and Bond's law for Jaw crusher.",
    status: "Functional",
    images: ["jaw-crusher-1.jpg"],
  },
  {
    labCategory: "Mechanical Unit Operation",
    name: "FT28 Oil Extraction Screw Press",
    description:
      "This oil extraction screw press has been developed to meet an increasing demand for a relatively unsophisticated small-capacity press, suitable for laboratory work. It is designed to press seeds, nuts or other fine biomass to extract the oil. In addition, a cake is formed which can be further purified downstream.",
    experiments: "It also helps to determine the cake thickness and oil yields.",
    status: "Functional",
    images: ["ft28-oil-extraction-screw-press-1.jpg"],
  },
  {
    labCategory: "Mechanical Unit Operation",
    name: "Solids Handling Studies Module - CEN-MKII",
    description:
      "The CEN-MKII consists of V-blender, ball mill, sieve, and cyclone. V-blender and ball mill have common units for the adjustment of speed during mixing and grinding respectivelyVee BlenderThe Vee blender is used to demonstrate blending of powdered materials together. The blender consists of a shallow V shaped vessel that is constructed from clear acrylic to aid viewing of the blending / mixing operation.Ball MillThe mill supplied consists of a PVC cylindrical drum that rotates in the horizontal plane. The two ends of the drum are constructed from clear acrylic to aid viewing of the milling operation.Vibratory Shaker and SievesThe granular materials with different particle sizes can be separated/ graded using a stack of sieves with different mesh sizes mounted on a vibratory shaker. After a period of operation, the different 'fractions' can be collected from each of the sieves and weighed using a suitable balance.Pneumatic Conveying and Cyclone separationThe apparatus provides a visual demonstration of the principles of pneumatic conveying using the cylindrical hopper as the cyclone. The low pressure created by a stream of compressed air from an external source (not supplied) through a Venturi is used to draw the granular material into the conveying system.",
    experiments:
      "EN-MKII-11 - Solids handlingReducing the size of granular material using a ball mill (comminution), Dry blending using a ball mill, examine the efficiency of mixing of granular materials (powder to powder) in a Vee blender CEN-MKII-12 - Powder handlingMeasuring bulk density, particle density and porosity (voidage) of granular materials, determine the bulk density of various solids and to examine the influence of moisture content and compaction of the bulk density, to determine the natural angle of repose for a variety of materials using a Hele-Shaw cell and to examine the influence of moisture content on the repose angle, to observe the natural stratification and agglomeration of various materials using a Hele-Shaw cell, to investigate how the discharge (flow) rate of solids from a hopper is related to the diameter of the issuing orifice and whether the head of material over the orifice has any effect on the flow rate, to demonstrate the operation of a pneumatic conveying system for solids and to show how a cyclone is used to separate the solids from the air streamCEN-MKII-13 - Solids handlingTo determine and analyse the size distribution of a fixed g",
    status: "Functional",
    images: [
      "solids-handling-studies-module-cen-mkii-1.jpg",
      "solids-handling-studies-module-cen-mkii-2.jpg",
      "solids-handling-studies-module-cen-mkii-3.jpg",
      "solids-handling-studies-module-cen-mkii-4.jpg",
    ],
  },
  {
    labCategory: "Mechanical Unit Operation",
    name: "UOP-12 Filtration Apparatus",
    description:
      "UOP12 is a benchtop unit designed to introduce students to the fundamentals of solid/liquid filtration. The apparatus consists of an acrylic feed tank connecting to a progressing cavity pump which feeds a slurry to the acrylic plate and frame filter press.",
    experiments:
      "Batch FiltrationDemonstrating Filtration through Plate and Frame filter Technology, understanding the principles of batch filtration using both constant pressure and constant flow operating modes, precoat Filtration, optimization of Filtration Performance using Body Aid, Darcy's Law, Determination of Medium and Cake Resistances, Effect of Body Aid on Medium and Cake ResistancesFilter Cake Washing and Dewatering, Economic Optimization of Filtration Operations (Scale up) and Mass Balancing.Continuous Filtration Demonstrating filtration through a hollow fibre cartridge system, Understanding the principles of continuous microfiltration, Examination of flux and transmission of a protein marker, Measurement of fouling and the effect on filtration performance",
    status: "Functional",
    images: ["uop-12-filtration-apparatus-1.jpg"],
  },
  {
    labCategory: "Mechanical Unit Operation",
    name: "W7 MKII Model Sedimentation Tank",
    description:
      "The W7MkII has been designed to demonstrate the hydraulic characteristics and settling efficiencies of a model settling basin. Although scale-up to industrial size sedimentation tanks is difficult, relevant deductions can be made as to how non-uniform flows occur and how these interact with the settling characteristics of particular suspensions.",
    experiments:
      "Measuring flow short circuiting and dead space using a tracer, Comparison of real flow regimes with idealized flow models, Effect of flowrate and baffle position on dispersion, measuring sediment removal efficiencies and relating these to hydraulic characteristics, Effect of solid concentration on separation efficiency, Use of the Imhoff cones for analysis.",
    status: "Functional",
    images: ["w7-mkii-model-sedimentation-tank-1.jpg"],
  },
  {
    labCategory: "Chemical Reaction and Biochemical Engineering Laboratory",
    name: "Reactors Common Service Unit",
    description: "",
    experiments: "It is served as a control and a process unit for other reactor types to investigate different parameters change on the reaction condition.",
    status: "Functional",
    images: ["reactors-common-service-unit-1.jpg"],
  },
  {
    labCategory: "Chemical Reaction and Biochemical Engineering Laboratory",
    name: "CEB Batch Reactor",
    description:
      "The CEB Batch Reactor is a double wall glass vessel with a 1L internal working volume, fitted with a variable-speed agitator, Conductivity and temperature probes. Hot water from the CEXC or cold water can be circulated through the jacket for the purposes of controlling temperature. demonstrated.",
    experiments:
      "Isothermal and adiabatic operation reactions may be demonstrated. Effect of temperature on reaction kinetics, Effect of concentration on conversion, Determination of the rate equation and activation energy through mass and energy balances and Study of temperature variation for exothermic reaction, can be",
    status: "Functional",
    images: ["ceb-batch-reactor-1.jpg"],
  },
  {
    labCategory: "Chemical Reaction and Biochemical Engineering Laboratory",
    name: "CEB CSTR reactor",
    description:
      "CEB CSTR reactor has adjustable volume between 0.4 and 1.5 liters using an adjustable standpipe. The temperature probe, conductivity probe and variable-speed mixer/agitator can be positioned in the reactor vessel along with baffles to improve the mixing. A stainless steel coil is used for temperature control of the reactor from the hot or cold water supply. The reagents are piped separately to the reactor through quick-release fittings.",
    experiments:
      "Effect of residence time on conversion, determination of reaction rate constant, residence time distribution, evaluation of empirical rate expressions from experimental data, effect of temperature and mixing on reaction rate, Effect of flow rates on conversion can be demonstrated",
    status: "Functional",
    images: ["ceb-cstr-reactor-1.jpg"],
  },
  {
    labCategory: "Chemical Reaction and Biochemical Engineering Laboratory",
    name: "CET-MKII Tubular reactor",
    description:
      "It is in the form of a tube (L=20 m and V=0.4L) wrapped in a spiral around an acrylic former, which is enclosed in a transparent tank. Water at a controlled temperature (from the CEXC) is circulated within the tank, this maintains the reactants at constant temperatures. The reagents are piped separately to the reactor through quick-release fittings mounted on the lid and are preheated in stainless steel coils in the water tank, before being mixed and fed into the reactor coil. Mounting positions are provided for the CEXC water temperature sensor (in the water tank) and the conductivity probe (at the reactor output) which measure the progress of the reaction.",
    experiments:
      "Determination of reaction rate constant, Investigation of the effect of throughput and flow rates on conversion, Demonstration of the temperature dependence of the reaction and the rate constant, Determination of the residence time distribution can be determined.",
    status: "Functional",
    images: ["cet-mkii-tubular-reactor-1.jpg"],
  },
  {
    labCategory: "Chemical Reaction and Biochemical Engineering Laboratory",
    name: "CEP-MKII - Stirred Tank Reactors in Series",
    description:
      "There are three reactor vessels connected in series, each containing a propeller agitator driven by a variable speed electric motor. It is designed to follow the dynamics of the perfectly mixed multistage process. Dynamic behaviour can be studied as can multistage chemical reaction.",
    experiments:
      "Investigation of dynamic behaviour of stirred tank reactors in series, Effect of step input change, Response to an impulse change, Influence of flow rate, Investigation of time constant using a dead time coil and Investigation of chemical reaction in a three-tank system",
    status: "Functional",
    images: ["cep-mkii-stirred-tank-reactors-in-series-1.jpg"],
  },
  {
    labCategory: "Chemical Reaction and Biochemical Engineering Laboratory",
    name: "CEU - Catalytic Reactors",
    description:
      "The CEU utilises the sugar inversion reaction (sucrose -> glucose + fructose) to study the performance of packed bed chemical and biological catalytic reactors. A colorimetric assay is used to determine the degree of conversion using an optical sensor. Assays may be automated using optional flow injection analysis..",
    experiments:
      "Understanding the principles of packed bed catalytic reactorsMass balancing, Examination of steady and unsteady state catalysis, Comparison of chemical and biological (enzymic) catalysis, Flow characterization in a packed bed, Understanding the principles of flow injection analysis (FIA)",
    status: "Functional",
    images: ["ceu-catalytic-reactors-1.jpg"],
  },
  {
    labCategory: "Chemical Reaction and Biochemical Engineering Laboratory",
    name: "BE1 Batch Enzyme Reactor",
    description:
      "It consists of a benchtop unit onto which is mounted a reactor vessel in which the glucose isomerase-mediated reaction takes place. The reactor itself is made of clear acrylic, which gives good visibility. A cruciform geometry impeller constructed from stainless steel mesh retains the immobilised enzyme while enabling efficient mixing with the liquid reactant (glucose solution).",
    experiments:
      "Determination of Michaelis-Menten constants and specific enzyme activity through Michaelis-Menten and Lineweaver-Burk plots, Determination of glucose and fructose concentrations through polarimetry, Effect of environmental conditions (pH and temperature) on enzyme activity, Demonstration of the Biot-Savart law, Understanding the principles of batch enzyme kinetics, Understanding the factors affecting enzyme performance, Understanding the principles of polarimetry and the Biot-Savart law",
    status: "Functional",
    images: ["be1-batch-enzyme-reactor-1.jpg"],
  },
  {
    labCategory: "Chemical Reaction and Biochemical Engineering Laboratory",
    name: "BE2 Chromatography Unit",
    description:
      "The BE2 consists of a benchtop unit onto which are mounted two 250mm long, 10mm diameter borosilicate glass chromatography columns. Both are equipped with adjustable end pieces to enable different bed heights to be investigated. On the top of each column are septum injectors to enable introduction of a sample onto the column surface. The columns are fed by a three-channel peristaltic pump of an eight-roller design in order to give smooth flow. The pump has a variable-speed drive and a wide range of tube bores can be used, thus giving a very wide flow rate range.",
    experiments:
      "Understanding the principles and practices of liquid chromatography, including (Column packing, Sample application, Column development, Analysis and fraction collection, Understanding the factors affecting separation performance, understanding protein concentration measurement through UV assays, Detailed teaching exercises are included to demonstrate to students the important aspects of size-exclusion (gel-filtration) chromatography. Information provided includes details of suitable gel matrices, buffers, proteins etc. and in-depth experimental protocols, although experiments relate to the size-exclusion method alone, the system is suitable for use with other low-pressure liquid chromatography systems such as ion-exchange, affinity and hydrophobic interaction, the system includes a UV flow cell for measurement of protein concentration. Level detection is 0.1 mg/ml of protein (bovine serum albumin), Understanding the protocols of running low-pressure liquid chromatography systems, Visual demonstration of size-exclusion chromatography using dyes, Determination of the effect of flow rate and column length on product separation and concentration",
    status: "Functional",
    images: ["be2-chromatography-unit-1.jpg"],
  },
  {
    labCategory: "Process Control and Fluid Mechanics",
    name: "PCT40 Process Control Apparatus",
    description:
      "It includes a variable volume process tank, a hot water tank with electric heater and indirect heating/cooling coil, a hot water pump, two non-dedicated pumps, three on/off solenoid valves and a proportioning valve. The instrumentation includes temperature sensors, two differential water pressure sensors, a mechanical level sensor (float switch) and an electronic level sensor (conductivity). The PCT40 includes a computer interface (USB), and all of the parameters can be controlled directly from the computer, (i.e. the pump speeds, the valve positions and the heater power). The computer also displays the readings from the various measurement sensors.",
    experiments:
      "The basic PCT40 is used under computer control to demonstrate a variety of single control loops. It can be quickly reconfigured between processes, such as level control, temperature control, flow control and pressure control. The advanced software enables the student to change the control parameters, record results and analyze the results for the different configurationsThe PCT41 expands on the capabilities of the PCT40, and offers a wider range of control loops and strategies, including remote set points, dual loops, and fluid property control (using conductivity). Again all of these are under software control",
    status: "Functional",
    images: ["pct40-process-control-apparatus-1.jpg"],
  },
  {
    labCategory: "Process Control and Fluid Mechanics",
    name: "PCT23MKII - Process Plant Trainer",
    description:
      "PCT23MKII can be used to demonstrate a complete range of process control methods and strategies. Manual control and single feedback loops through to sophisticated cascade loops can be demonstrated along with distributed supervisory control of the whole process, by a remotely located computer.The system is a miniature replication of a true production process. The student is presented with real process control problems with realistic dynamic behaviour and instabilities.",
    experiments:
      "Plant Monitoring using a PC, Calibration of Sensors Process Dynamics I (Steady State Operation (Direct Heating), indirect Heat Exchange, Dead, Step Changes Heat Transfer Losses), Process Dynamics II (Interaction, Heat Regeneration, Indirect Cooling, Process Duty, PID Control of Level using Software, PID Control of Flow using Software, PID Control of Temperature using Software, PID Control of Conductivity using Software, Indirect PID Control, PID Control of Temperature with Dead Time, PID Control with Alarm Driven Disturbances, Controller Optimization, Controller Optimization with Dead Time, Two Loop Cascade Control, Two Loop Control and Interaction, Three Loop Control, Fault Finding and Diagnostics)",
    status: "Functional",
    images: ["pct23mkii-process-plant-trainer-1.jpg", "pct23mkii-process-plant-trainer-2.jpg"],
  },
  {
    labCategory: "Process Control and Fluid Mechanics",
    name: "FM6X - Turbine Service Unit",
    description:
      "The FM6X Turbine Service unit provides a pressurized high flow water supply, which is required to operate the FM60, FM61 and FM62 turbine demonstration modules. The turbine under test is connected to the dynamometer by a toothed drive belt. Load is applied to the turbine using a magnetic brake controlled directly from the computer. The outer casing of the brake is restrained from rotating by a lever arm, which is connected to a load cell. This enables the braking force and the torque produced to be directly measured. The dynamometer unit also incorporates an optical sensor, which measures the rotational speed of the turbine.",
    experiments:
      "Determining the characteristics of the selected turbine, including the relationships of volume flow rate, head, torque produced, power output and efficiency to rotational speed (FM60/FM61/FM62), Comparison of nozzle and throttling control of an Impulse Turbine (FM60), Comparison of throttle control and spear valve control of the speed of a Pelton Turbine (FM62), Determination of characteristic performance curves for a peripheral pump, including constant speed head/flow and efficiency curves (FM64)",
    status: "Functional",
    images: ["fm6x-turbine-service-unit-1.jpg"],
  },
  {
    labCategory: "Heat and Mass Transfer laboratory",
    name: "HT37E - Extended Plate Heat Exchanger",
    description:
      "The HT37X is designed to be reconfigurable and can accommodate up to four sections of heating. Plate heat exchangers can be implemented in a wide variety of configurations, with parallel passes, serial passes, or combinations of both. These can be used in conjunction with the plates from the pre-assembled modules to investigate additional configurations.",
    experiments: "A small scale plate heat exchanger system for use with an Armfield Heat Exchange Service Unit to teach the fundamental concepts of heat exchangers",
    status: "Functional",
    images: ["ht37e-extended-plate-heat-exchanger-1.jpg"],
  },
  {
    labCategory: "Heat and Mass Transfer laboratory",
    name: "HT37X - Extended Plate Heat Exchanger",
    description:
      "The tubular heat exchanger is the simplest form of heat exchanger and consists of two concentric (coaxial) tubes carrying the hot and cold fluids. In these miniature versions the tubes are separated into sections to reduce the overall length and to enable the temperature at points along both fluid streams to be measured. The HT36X unit has four longer tube sections, giving four times the overall heat transfer area and three interim temperature measurement points in each fluid stream.",
    experiments: "A small scale Tubular Heat Exchanger system for use with an Computer Controlled Armfield Heat Exchange Service Unit to teach the fundamental concepts of heat exchangers",
    status: "Functional",
    images: ["ht37x-extended-plate-heat-exchanger-1.jpg"],
  },
  {
    labCategory: "Heat and Mass Transfer laboratory",
    name: "HT-34 Jacketed Vessel With Coil & Stirrer",
    description:
      "Vessel Heating or cooling of a process liquid in a tank, either batchwise or with continuous product feed, is common practice throughout industry. The characteristics of the heat transfer using an external jacket or internal coil can be demonstrated together with the effect of stirring the vessel contents",
    experiments: "A small scale Jacketed Vessel Heat Exchanger system for use with an Computer Controlled Armfield Heat Exchange Service Unit to teach the fundamental concepts of heat exchangers",
    status: "Functional",
    images: ["ht-34-jacketed-vessel-with-coil-stirrer-1.jpg"],
  },
  {
    labCategory: "Heat and Mass Transfer laboratory",
    name: "CH-10.5 Laboratory Distillation Pilot Plant",
    description:
      "Laboratory Distillation Pilot Plant enables safe hands-on practical training for students and plant operators as well as empowering research in different fields to be conducted. The pilot plant has designed with two distillation column options; batch distillation column and continuous distillation column.",
    experiments:
      "Pressure drop across the column, Column efficiency as a function of boil-up rate at total reflux plate-to-plate temperature profiles along the column, McCabe-Thiele construction of operating line, Distillation at constant reflux ratio: variation of top product composition with time, Mass balance across the system, Manual control of reflux ratio; for example, to achieve a top product of specified compositionComparison of packed column with sieve plate column performance, Continuous steady state distillation including temperature profiles and McCabe-Thiele analysis, Effect of feed pre-heat, Effect of feed position, Demonstration of azeotropic distillation",
    status: "Functional",
    images: ["ch-10-5-laboratory-distillation-pilot-plant-1.jpg"],
  },
  {
    labCategory: "Heat and Mass Transfer laboratory",
    name: "CE 715 Rising Film Evaporation",
    description:
      "The CE 715 allows the operating behavior of a rising film evaporator to be investigated. The untreated solution is fed from the feed tank below into the evaporator. The evaporator is a double pipe heat exchanger that is heated by steam. The steam pressure on the casing side is adjusted with a PID controller. A cyclone is installed after the evaporator to separate the evaporated solvent and the concentrated solution. The solvent vapour removed is condensed in a water-cooled condenser and collected in a tank. The concentrated solution can also be collected in a tank or fed back into the evaporator for the concentration to be increased further.",
    experiments:
      "Fundamental principle of film evaporation for increasing the concentration of temperature-sensitive solutions, investigation of the variables influencing the solid concentration in the solution, influence of pressure and feed flow rate on the separating process, influence of flow rate and pressure of the heating steam on the separating process, investigation of the variables influencing the energy efficiency of the processenergy balances at heat exchangers, system cleaning while installed",
    status: "Functional",
    images: ["ce-715-rising-film-evaporation-1.jpg"],
  },
  {
    labCategory: "Heat and Mass Transfer laboratory",
    name: "CH-16.1 Liquid-Liquid Extraction Unit",
    description:
      "Liquid / liquid extraction is an important operation in chemical engineering where the separation of one or more of the components from a liquid mixture is required. The unit comprises a glass separation column, packed with glass Raschig rings which provide a large surface area for the extraction process. Four process tanks are included, a feed tank and collection tank for the organic phase and a feed tank and collection tank for the aqueous phase. It has also simple distillation apparats embedded with it to separate components which have large boiling point difference.",
    experiments:
      "Hydrodynamics of a packed liquid / liquid extraction column, Differences in extraction performance using the organic phase or the aqueous phase as the continuous phase, Investigation into the effect of changes in aqueous and organic flow rateMass balances and the calculation of mass transfer coefficient",
    status: "Partially Functional",
    images: ["ch-16-1-liquid-liquid-extraction-unit-1.jpg"],
  },
  {
    labCategory: "Heat and Mass Transfer laboratory",
    name: "Liquid-Gas absorption",
    description:
      "The Gas Absorption Column has been designed to demonstrate the principles of gas absorption and to provide practical training in the operation of a gas absorption plant. In the process of gas absorption, a mixture of gases is contacted with a liquid, for the purpose of dissolving one or more components of the gas and to provide a solution of them into the liquid.",
    experiments:
      "Study of basic principles of the absorption of a gas into a liquid using a packed column, Determination of loading and flooding points, Study of hydrodynamic characteristics of a packed column, Demonstration of physical and chemical absorptionInvestigation of the effectiveness of CO2 absorption in pure water and in an aqueous solution, Demonstration of gas desorption, Determination of the mass transfer coefficient",
    status: "Functional",
    images: [],
  },
  {
    labCategory: "Heat and Mass Transfer laboratory",
    name: "UOP14-Crystalization Unit",
    description:
      "It is a bench-top unit with the see-through glass crystallization reactor which allows visualization of crystallization phenomena. UOP14 utilizes the solution cooling method to study the crystallizer performance. The equipment consists of a jacketed crystallization vessel provided with temperature control and agitation. The crystallization reactor is thermally controlled by means of heated water circulating in the reactor jacket. The water is heated by an in-line heater. The temperature sensor within the reactor and the heater are linked to a 3 term PID controller which is programmed to maintain the desired set-point temperature.",
    experiments:
      "Understanding the principles of crystallization, Mass and energy balancing, Batch operation, Continuous operation (option), Evaluation of crystallization efficiency and crystallization kinetics, Study of the effect of different parameters: agitation rate, cooling rate, Crystal size distribution",
    status: "Functional",
    images: ["uop14-crystalization-unit-1.jpg"],
  },
  {
    labCategory: "Heat and Mass Transfer laboratory",
    name: "CERa-MKII - Gaseous Diffusion Coefficient Apparatus",
    description: "CERa-MKII apparatus is used to investigate mass transfer and gaseous diffusion using modern computer compatible microscopy, producing a novel system with a large number of benefits.",
    experiments:
      "To determine the diffusion coefficient of a gas by evaporation from a liquid surface, Direct measurement of mass transfer rates in the absence of convective effects, Use of gas laws to calculate concentration differences in terms of partial pressures, Use of Fick's law to measure diffusion coefficients in the presence of a stationary gas, Measurement of the effect of temperature on diffusion coefficients, Investigation into diffusion coefficients of alternative fluids, Gaining familiarity with the use of laboratory instruments to achieve accurate measurements of data required for industrial process design.",
    status: "Functional",
    images: ["cera-mkii-gaseous-diffusion-coefficient-apparatus-1.jpg"],
  },
  {
    labCategory: "Heat and Mass Transfer laboratory",
    name: "CERb - Liquid Diffusion Coefficient Apparatus",
    description: "The liquid diffusivities coefficient apparatus laboratory equipment has been designed to enable measurement of molecular diffusivities relating to an equimolar counter-diffusion process and in so doing, familiarize students with the basic notions of mass transfer theory.",
    experiments:
      "To determine the diffusion coefficient of a gas by evaporation from a liquid surface, Direct measurement of mass transfer rates in the absence of convective effects, Use of gas laws to calculate concentration differences in terms of partial pressures, Use of Fick's law to measure diffusion coefficients in the presence of a stationary gas, Measurement of the effect of temperature on diffusion coefficients, Investigation into diffusion coefficients of alternative fluids, Gaining familiarity with the use of laboratory instruments to achieve accurate measurements of data required for industrial process design.",
    status: "Functional",
    images: ["cerb-liquid-diffusion-coefficient-apparatus-1.jpg"],
  },
  {
    labCategory: "Heat and Mass Transfer laboratory",
    name: "CH-17 Solid Liquid Extraction Unit",
    description:
      "The unit utilizes a sophisticated, continuous feed, counter-current flow, multiple-stage, rotary extractor system of the type frequently seen in industrial applications. This gives the student an insight into the practical implementation of the operation, including process economics and control problems. The effects of temperature, multiple stages, and throughput rate can all be investigated.",
    experiments:
      "Demonstration of the operation of a continuous multiple-stage process, Closed-circuit percolation extraction (batch extraction), Open-loop percolation extraction (continuous operation), Investigation of continuous extraction in 1, 2 or 3 steps, Investigation into effect of solvent temperatures, Investigation into effect of solvent flow rates, investigation into effect of processing time, Process economics and mass balances",
    status: "Functional",
    images: ["ch-17-solid-liquid-extraction-unit-1.jpg"],
  },
  {
    labCategory: "Heat and Mass Transfer laboratory",
    name: "UOP15 Fixed Bed Adsorption Unit",
    description: "The UOP15 introduces students to the fundamentals of adsorption and desorption processes using a packed bed reactor. The unit is fitted with a stainless steel reactor column in which the adsorbent, activated carbon, is packed",
    experiments:
      "Teaching exercises are included to familiarise students with the following principles:Study of the adsorption/desorption processes under different operational conditions: temperature, flow rate, molar fraction and pressure, Study of the breakthrough curves of temperature profiles during the adsorption/desorption process, Study of the quasi-isothermal regime at low concentrations and pressures, Study of the solute movement theory model, which describes the adsorption/desorption process, Familiarisation with the formation of the compressive and dispersive fronts in adsorption processes, Analysis of the breakthrough curves of CO2 during the adsorption and desorption/regeneration processes, Obtain the adsorption equilibrium isotherm of CO2 from the desorption curve (dispersive wave)",
    status: "Functional",
    images: ["uop15-fixed-bed-adsorption-unit-1.jpg"],
  },
  {
    labCategory: "Heat and Mass Transfer laboratory",
    name: "CES - Wetted Wall Gas Absorption Column",
    description:
      "Wetted wall columns may be used to determine gas/liquid mass transfer coefficients, essential when calculating the design of absorption towers. Such coefficients form the basis of correlations used to develop packed towers. CES examines the absorption of oxygen from air into deoxygenated water prepared by nitrogen sparging). This is an example of liquid film controlled absorption. The liquid film mass transfer coefficient can be determined at various mass flow rates of water.",
    experiments:
      "Calculation of liquid film mass transfer coefficients, Variation of coefficient with mass flow rate, Variation of oxygen flow rate to determine power law relationship,To determine the power-law relationship between the liquid film mass transfer coefficient",
    status: "Functional",
    images: ["ces-wetted-wall-gas-absorption-column-1.jpg"],
  },
  {
    labCategory: "Heat and Mass Transfer laboratory",
    name: "CH-70 Tray Dryer Training Unit",
    description: "This the unit is a standalone tray dryer is designed to dry solids by passing a stream of hot air over trays of wet material, a method commonly used in industry.I t is applicable to the unit operations laboratory and also to food technology education and research.",
    experiments: "Demonstration of drying rate regimes, Heat and mass transferDrying tests on solids for industrial use, Effect of temperature and air velocity on drying rates, Use of psychrometric charts",
    status: "Functional",
    images: ["ch-70-tray-dryer-training-unit-1.jpg"],
  },
  {
    labCategory: "Heat and Mass Transfer laboratory",
    name: "CH-21 Ion Exchanger Unit",
    description: "The unit consists of two vertical transparent columns containing the cation and anion resins. Conductivity, temperature and pH of the influent and effluent of the columns are measured using electronic sensors for data logging.",
    experiments:
      "Water softening using cationic resin, Exchange capacity of a cationic softening system, Regeneration efficiency of a cationic softening system (regenerated using NaCl), Demineralisation using two-bed exchange (cationic resin and anionic resin used in series), Regeneration efficiency of a demineralization system.",
    status: "Semi Functional",
    images: ["ch-21-ion-exchanger-unit-1.jpg"],
  },
];
